/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2015-07-23 09:17:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.atlassian.jira.config.properties.APKeys;
import com.atlassian.jira.config.properties.ApplicationProperties;
import com.atlassian.jira.security.JiraAuthenticationContext;
import com.atlassian.jira.util.I18nHelper;
import com.atlassian.jira.web.filters.steps.senderror.CaptureSendErrorMessageResponseWrapper;
import com.atlassian.jira.component.ComponentAccessor;
import com.atlassian.jira.web.util.ProductVersionDataBeanProvider;
import com.atlassian.plugin.webresource.WebResourceManager;
import com.opensymphony.util.TextUtils;
import com.atlassian.jira.component.ComponentAccessor;
import com.atlassian.jira.plugin.navigation.HeaderFooterRendering;

public final class _404page_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/webwork.tld", Long.valueOf(1374535548000L));
    _jspx_dependants.put("/includes/decorators/aui-layout/head-resources.jsp", Long.valueOf(1374535548000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fui_005fparam_0026_005fname;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.release();
    _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");

    final I18nHelper i18nBean = ComponentAccessor.getComponent(JiraAuthenticationContext.class).getI18nHelper();
    WebResourceManager webResourceManager = ComponentAccessor.getComponent(WebResourceManager.class);
    webResourceManager.requireResourcesForContext("atl.general");
    webResourceManager.requireResourcesForContext("jira.general");
    String msg = (String) request.getAttribute(CaptureSendErrorMessageResponseWrapper.CAPTURED_MESSAGE_REQUEST_ATTR);
    msg = TextUtils.htmlEncode(msg);

    ApplicationProperties applicationProperties = ComponentAccessor.getComponent(ApplicationProperties.class);
    final String jiraTitle = applicationProperties.getDefaultBackedString(APKeys.JIRA_TITLE);
    final String jiraLogoUrl = applicationProperties.getDefaultBackedString(APKeys.JIRA_LF_LOGO_URL);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge;chrome=1\" />\n");
      out.write("    <title>");
      out.print(TextUtils.htmlEncode(i18nBean.getText("404.title")));
      out.write(" (404)</title>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--[if IE]><![endif]-->");
      out.write("\n");
      out.write("<script type=\"text/javascript\">var contextPath = '");
      out.print(request.getContextPath());
      out.write("';</script>\n");

    //
    // IDEA gives you a warning below because it cant resolve JspWriter.  I don't know why but its harmless
    //
    HeaderFooterRendering headerAndFooter = ComponentAccessor.getComponent(HeaderFooterRendering.class);

    headerAndFooter.includeHeadResources(out);

      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(headerAndFooter.getKeyboardShortCutScript(request) );
      out.write("\"></script>\n");

    headerAndFooter.includeWebPanels(out, "atl.header.after.scripts");

      out.write('\n');
      out.write("\n");
      out.write("    ");
      out.print( ComponentAccessor.getComponent(ProductVersionDataBeanProvider.class).get().getMetaTags() );
      out.write("\n");
      out.write("</head>\n");
      out.write("<body id=\"jira\" class=\"aui-layout aui-theme-default page-type-message\" ");
      out.print( ComponentAccessor.getComponent(ProductVersionDataBeanProvider.class).get().getBodyHtmlAttributes() );
      out.write(" >\n");
      out.write("<div id=\"page\">\n");
      out.write("    <header id=\"header\" role=\"banner\">\n");
      out.write("        <nav class=\"aui-header aui-dropdown2-trigger-group\" role=\"navigation\">\n");
      out.write("            <div class=\"aui-header-inner\">\n");
      out.write("                <div class=\"aui-header-primary\">\n");
      out.write("                    <h1 id=\"logo\" class=\"aui-header-logo\">\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/secure/MyJiraHome.jspa\"><img src=\"");
      out.print(request.getContextPath() + TextUtils.htmlEncode(jiraLogoUrl));
      out.write("\" alt=\"");
      out.print(TextUtils.htmlEncode(jiraTitle));
      out.write("\" /></a>\n");
      out.write("                    </h1>\n");
      out.write("                </div>\n");
      out.write("            </div><!-- .aui-header-inner-->\n");
      out.write("        </nav><!-- .aui-header -->\n");
      out.write("    </header>\n");
      out.write("    <section id=\"content\" role=\"main\">\n");
      out.write("        ");
      //  ui:soy
      com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f0 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
      _jspx_th_ui_005fsoy_005f0.setPageContext(_jspx_page_context);
      _jspx_th_ui_005fsoy_005f0.setParent(null);
      // /404page.jsp(47,8) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f0.setModuleKey("'com.atlassian.auiplugin:aui-experimental-soy-templates'");
      // /404page.jsp(47,8) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_ui_005fsoy_005f0.setTemplate("'aui.page.pagePanel'");
      int _jspx_eval_ui_005fsoy_005f0 = _jspx_th_ui_005fsoy_005f0.doStartTag();
      if (_jspx_eval_ui_005fsoy_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_ui_005fsoy_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_ui_005fsoy_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_ui_005fsoy_005f0.doInitBody();
        }
        do {
          out.write("\n");
          out.write("            ");
          //  ui:param
          webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f0 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
          _jspx_th_ui_005fparam_005f0.setPageContext(_jspx_page_context);
          _jspx_th_ui_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f0);
          // /404page.jsp(48,12) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_ui_005fparam_005f0.setName("'content'");
          int _jspx_eval_ui_005fparam_005f0 = _jspx_th_ui_005fparam_005f0.doStartTag();
          if (_jspx_eval_ui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_ui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_ui_005fparam_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_ui_005fparam_005f0.doInitBody();
            }
            do {
              out.write("\n");
              out.write("                ");
              //  ui:soy
              com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f1 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
              _jspx_th_ui_005fsoy_005f1.setPageContext(_jspx_page_context);
              _jspx_th_ui_005fsoy_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f0);
              // /404page.jsp(49,16) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_ui_005fsoy_005f1.setModuleKey("'com.atlassian.auiplugin:aui-experimental-soy-templates'");
              // /404page.jsp(49,16) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_ui_005fsoy_005f1.setTemplate("'aui.page.pagePanelContent'");
              int _jspx_eval_ui_005fsoy_005f1 = _jspx_th_ui_005fsoy_005f1.doStartTag();
              if (_jspx_eval_ui_005fsoy_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_ui_005fsoy_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.pushBody();
                  _jspx_th_ui_005fsoy_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                  _jspx_th_ui_005fsoy_005f1.doInitBody();
                }
                do {
                  out.write("\n");
                  out.write("                    ");
                  //  ui:param
                  webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f1 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                  _jspx_th_ui_005fparam_005f1.setPageContext(_jspx_page_context);
                  _jspx_th_ui_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f1);
                  // /404page.jsp(50,20) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                  _jspx_th_ui_005fparam_005f1.setName("'content'");
                  int _jspx_eval_ui_005fparam_005f1 = _jspx_th_ui_005fparam_005f1.doStartTag();
                  if (_jspx_eval_ui_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                    if (_jspx_eval_ui_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                      out = _jspx_page_context.pushBody();
                      _jspx_th_ui_005fparam_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                      _jspx_th_ui_005fparam_005f1.doInitBody();
                    }
                    do {
                      out.write("\n");
                      out.write("                        ");
                      //  ui:soy
                      com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f2 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
                      _jspx_th_ui_005fsoy_005f2.setPageContext(_jspx_page_context);
                      _jspx_th_ui_005fsoy_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f1);
                      // /404page.jsp(51,24) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                      _jspx_th_ui_005fsoy_005f2.setModuleKey("'com.atlassian.auiplugin:aui-experimental-soy-templates'");
                      // /404page.jsp(51,24) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                      _jspx_th_ui_005fsoy_005f2.setTemplate("'aui.page.pageHeader'");
                      int _jspx_eval_ui_005fsoy_005f2 = _jspx_th_ui_005fsoy_005f2.doStartTag();
                      if (_jspx_eval_ui_005fsoy_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                        if (_jspx_eval_ui_005fsoy_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                          out = _jspx_page_context.pushBody();
                          _jspx_th_ui_005fsoy_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                          _jspx_th_ui_005fsoy_005f2.doInitBody();
                        }
                        do {
                          out.write("\n");
                          out.write("                            ");
                          //  ui:param
                          webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f2 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                          _jspx_th_ui_005fparam_005f2.setPageContext(_jspx_page_context);
                          _jspx_th_ui_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f2);
                          // /404page.jsp(52,28) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_ui_005fparam_005f2.setName("'content'");
                          int _jspx_eval_ui_005fparam_005f2 = _jspx_th_ui_005fparam_005f2.doStartTag();
                          if (_jspx_eval_ui_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            if (_jspx_eval_ui_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.pushBody();
                              _jspx_th_ui_005fparam_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                              _jspx_th_ui_005fparam_005f2.doInitBody();
                            }
                            do {
                              out.write("\n");
                              out.write("                                ");
                              //  ui:soy
                              com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f3 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
                              _jspx_th_ui_005fsoy_005f3.setPageContext(_jspx_page_context);
                              _jspx_th_ui_005fsoy_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f2);
                              // /404page.jsp(53,32) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fsoy_005f3.setModuleKey("'com.atlassian.auiplugin:aui-experimental-soy-templates'");
                              // /404page.jsp(53,32) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fsoy_005f3.setTemplate("'aui.page.pageHeaderMain'");
                              int _jspx_eval_ui_005fsoy_005f3 = _jspx_th_ui_005fsoy_005f3.doStartTag();
                              if (_jspx_eval_ui_005fsoy_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ui_005fsoy_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.pushBody();
                              _jspx_th_ui_005fsoy_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                              _jspx_th_ui_005fsoy_005f3.doInitBody();
                              }
                              do {
                              out.write("\n");
                              out.write("                                    ");
                              //  ui:param
                              webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f3 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                              _jspx_th_ui_005fparam_005f3.setPageContext(_jspx_page_context);
                              _jspx_th_ui_005fparam_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f3);
                              // /404page.jsp(54,36) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_ui_005fparam_005f3.setName("'content'");
                              int _jspx_eval_ui_005fparam_005f3 = _jspx_th_ui_005fparam_005f3.doStartTag();
                              if (_jspx_eval_ui_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                              if (_jspx_eval_ui_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.pushBody();
                              _jspx_th_ui_005fparam_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                              _jspx_th_ui_005fparam_005f3.doInitBody();
                              }
                              do {
                              out.write("\n");
                              out.write("                                        <h1>");
                              out.print(TextUtils.htmlEncode(i18nBean.getText("404.title")));
                              out.write(" (404)</h1>\n");
                              out.write("                                    ");
                              int evalDoAfterBody = _jspx_th_ui_005fparam_005f3.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ui_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ui_005fparam_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f3);
                              return;
                              }
                              _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f3);
                              out.write("\n");
                              out.write("                                ");
                              int evalDoAfterBody = _jspx_th_ui_005fsoy_005f3.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                              } while (true);
                              if (_jspx_eval_ui_005fsoy_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                              }
                              }
                              if (_jspx_th_ui_005fsoy_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f3);
                              return;
                              }
                              _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f3);
                              out.write("\n");
                              out.write("                            ");
                              int evalDoAfterBody = _jspx_th_ui_005fparam_005f2.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_ui_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                            }
                          }
                          if (_jspx_th_ui_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f2);
                            return;
                          }
                          _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f2);
                          out.write("\n");
                          out.write("                        ");
                          int evalDoAfterBody = _jspx_th_ui_005fsoy_005f2.doAfterBody();
                          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                            break;
                        } while (true);
                        if (_jspx_eval_ui_005fsoy_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                          out = _jspx_page_context.popBody();
                        }
                      }
                      if (_jspx_th_ui_005fsoy_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                        _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f2);
                        return;
                      }
                      _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f2);
                      out.write("\n");
                      out.write("                        ");
                      //  ui:soy
                      com.atlassian.jira.web.tags.SoyTemplateTag _jspx_th_ui_005fsoy_005f4 = (com.atlassian.jira.web.tags.SoyTemplateTag) _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.get(com.atlassian.jira.web.tags.SoyTemplateTag.class);
                      _jspx_th_ui_005fsoy_005f4.setPageContext(_jspx_page_context);
                      _jspx_th_ui_005fsoy_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fparam_005f1);
                      // /404page.jsp(60,24) name = moduleKey type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                      _jspx_th_ui_005fsoy_005f4.setModuleKey("'com.atlassian.auiplugin:aui-experimental-soy-templates'");
                      // /404page.jsp(60,24) name = template type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                      _jspx_th_ui_005fsoy_005f4.setTemplate("'aui.message.warning'");
                      int _jspx_eval_ui_005fsoy_005f4 = _jspx_th_ui_005fsoy_005f4.doStartTag();
                      if (_jspx_eval_ui_005fsoy_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                        if (_jspx_eval_ui_005fsoy_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                          out = _jspx_page_context.pushBody();
                          _jspx_th_ui_005fsoy_005f4.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                          _jspx_th_ui_005fsoy_005f4.doInitBody();
                        }
                        do {
                          out.write("\n");
                          out.write("                            ");
                          //  ui:param
                          webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f4 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                          _jspx_th_ui_005fparam_005f4.setPageContext(_jspx_page_context);
                          _jspx_th_ui_005fparam_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f4);
                          // /404page.jsp(61,28) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_ui_005fparam_005f4.setName("'titleContent'");
                          int _jspx_eval_ui_005fparam_005f4 = _jspx_th_ui_005fparam_005f4.doStartTag();
                          if (_jspx_eval_ui_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            if (_jspx_eval_ui_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.pushBody();
                              _jspx_th_ui_005fparam_005f4.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                              _jspx_th_ui_005fparam_005f4.doInitBody();
                            }
                            do {
                              out.print(msg);
                              int evalDoAfterBody = _jspx_th_ui_005fparam_005f4.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_ui_005fparam_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                            }
                          }
                          if (_jspx_th_ui_005fparam_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f4);
                            return;
                          }
                          _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f4);
                          out.write("\n");
                          out.write("                            ");
                          //  ui:param
                          webwork.view.taglib.ParamTag _jspx_th_ui_005fparam_005f5 = (webwork.view.taglib.ParamTag) _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.get(webwork.view.taglib.ParamTag.class);
                          _jspx_th_ui_005fparam_005f5.setPageContext(_jspx_page_context);
                          _jspx_th_ui_005fparam_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_ui_005fsoy_005f4);
                          // /404page.jsp(62,28) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_ui_005fparam_005f5.setName("'content'");
                          int _jspx_eval_ui_005fparam_005f5 = _jspx_th_ui_005fparam_005f5.doStartTag();
                          if (_jspx_eval_ui_005fparam_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            if (_jspx_eval_ui_005fparam_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.pushBody();
                              _jspx_th_ui_005fparam_005f5.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                              _jspx_th_ui_005fparam_005f5.doInitBody();
                            }
                            do {
                              out.write("\n");
                              out.write("                                <p>");
                              out.print(TextUtils.htmlEncode(i18nBean.getText("404.message")));
                              out.write("</p>\n");
                              out.write("                                <p><a href=\"");
                              out.print(request.getContextPath());
                              out.write("/secure/MyJiraHome.jspa\">");
                              out.print(TextUtils.htmlEncode(i18nBean.getText("admin.keyboard.shortcut.goto.homr.desc")));
                              out.write("</a></p>\n");
                              out.write("                            ");
                              int evalDoAfterBody = _jspx_th_ui_005fparam_005f5.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                            if (_jspx_eval_ui_005fparam_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                              out = _jspx_page_context.popBody();
                            }
                          }
                          if (_jspx_th_ui_005fparam_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f5);
                            return;
                          }
                          _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f5);
                          out.write("\n");
                          out.write("                        ");
                          int evalDoAfterBody = _jspx_th_ui_005fsoy_005f4.doAfterBody();
                          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                            break;
                        } while (true);
                        if (_jspx_eval_ui_005fsoy_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                          out = _jspx_page_context.popBody();
                        }
                      }
                      if (_jspx_th_ui_005fsoy_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                        _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f4);
                        return;
                      }
                      _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f4);
                      out.write("\n");
                      out.write("                    ");
                      int evalDoAfterBody = _jspx_th_ui_005fparam_005f1.doAfterBody();
                      if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                        break;
                    } while (true);
                    if (_jspx_eval_ui_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                      out = _jspx_page_context.popBody();
                    }
                  }
                  if (_jspx_th_ui_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f1);
                    return;
                  }
                  _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f1);
                  out.write("\n");
                  out.write("                ");
                  int evalDoAfterBody = _jspx_th_ui_005fsoy_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_ui_005fsoy_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_ui_005fsoy_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f1);
                return;
              }
              _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f1);
              out.write("\n");
              out.write("            ");
              int evalDoAfterBody = _jspx_th_ui_005fparam_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_ui_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_ui_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fui_005fparam_0026_005fname.reuse(_jspx_th_ui_005fparam_005f0);
          out.write("\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_ui_005fsoy_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_ui_005fsoy_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_ui_005fsoy_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fui_005fsoy_0026_005ftemplate_005fmoduleKey.reuse(_jspx_th_ui_005fsoy_005f0);
      out.write("\n");
      out.write("    </section>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
